name: Purge Auto-GPT Docker CI cache
 
on: 
  workflow_dispatch:
 
env:
  BASE_BRANCH: development
  IMAGE_NAME: auto-gpt
 
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: [release, dev]
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
 
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
 
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
 
    - id: build
      name: Build and Push image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ matrix.build-type }}
        file: Dockerfile.autogpt
        build-args: BUILD_TYPE=${{ matrix.build-type }}
        cache-from: type=gha,scope=autogpt-docker-${{ matrix.build-type }} 
        cache-to: type=gha,scope=autogpt-docker-${{ matrix.build-type }},mode=max
        buildx-args: "--platform linux/amd64,linux/arm64,linux/arm/v7"
